<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2026.8.0" />
    <ProjectReference Include="..\InventarioRopa.DAL\InventarioRopa.DAL.csproj" />
    <ProjectReference Include="..\InventarioRopa.Entities\InventarioRopa.Entities.csproj" />
  </ItemGroup>
</Project>
